/* 
 * Stocks
 *
 * <h3>Rate limits</h3>                     Free subscriptions are subject to daily limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)<br />                     2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: contact@equibles.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Equibles.Stocks.Client;
using Equibles.Stocks.Model;

namespace Equibles.Stocks.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IStocksApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List Stocks
        /// </summary>
        /// <remarks>
        /// Get a list of all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>StockProfilesResponse</returns>
        StockProfilesResponse CallList (string apiKey, int? page, int? pageSize);

        /// <summary>
        /// List Stocks
        /// </summary>
        /// <remarks>
        /// Get a list of all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>ApiResponse of StockProfilesResponse</returns>
        ApiResponse<StockProfilesResponse> CallListWithHttpInfo (string apiKey, int? page, int? pageSize);
        /// <summary>
        /// Officers
        /// </summary>
        /// <remarks>
        /// Get the officers of the company.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>OfficersResponse</returns>
        OfficersResponse Officers (string apiKey, string fullTicker);

        /// <summary>
        /// Officers
        /// </summary>
        /// <remarks>
        /// Get the officers of the company.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>ApiResponse of OfficersResponse</returns>
        ApiResponse<OfficersResponse> OfficersWithHttpInfo (string apiKey, string fullTicker);
        /// <summary>
        /// Profile
        /// </summary>
        /// <remarks>
        /// Returns the profile of a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>StockProfileResponse</returns>
        StockProfileResponse Profile (string apiKey, string fullTicker);

        /// <summary>
        /// Profile
        /// </summary>
        /// <remarks>
        /// Returns the profile of a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>ApiResponse of StockProfileResponse</returns>
        ApiResponse<StockProfileResponse> ProfileWithHttpInfo (string apiKey, string fullTicker);
        /// <summary>
        /// Screener
        /// </summary>
        /// <remarks>
        /// Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>StockProfilesResponse</returns>
        StockProfilesResponse Screener (ScreenerRequest body, string apiKey, int? page, int? pageSize);

        /// <summary>
        /// Screener
        /// </summary>
        /// <remarks>
        /// Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>ApiResponse of StockProfilesResponse</returns>
        ApiResponse<StockProfilesResponse> ScreenerWithHttpInfo (ScreenerRequest body, string apiKey, int? page, int? pageSize);
        /// <summary>
        /// Search
        /// </summary>
        /// <remarks>
        /// Search among all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>StockProfilesResponse</returns>
        StockProfilesResponse Search (string apiKey, string text, int? page, int? pageSize);

        /// <summary>
        /// Search
        /// </summary>
        /// <remarks>
        /// Search among all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>ApiResponse of StockProfilesResponse</returns>
        ApiResponse<StockProfilesResponse> SearchWithHttpInfo (string apiKey, string text, int? page, int? pageSize);
        /// <summary>
        /// Splits
        /// </summary>
        /// <remarks>
        /// Get all the splits for a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>SplitsResponse</returns>
        SplitsResponse Splits (string apiKey, string fullTicker, int? page, int? pageSize);

        /// <summary>
        /// Splits
        /// </summary>
        /// <remarks>
        /// Get all the splits for a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>ApiResponse of SplitsResponse</returns>
        ApiResponse<SplitsResponse> SplitsWithHttpInfo (string apiKey, string fullTicker, int? page, int? pageSize);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// List Stocks
        /// </summary>
        /// <remarks>
        /// Get a list of all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of StockProfilesResponse</returns>
        System.Threading.Tasks.Task<StockProfilesResponse> CallListAsync (string apiKey, int? page, int? pageSize);

        /// <summary>
        /// List Stocks
        /// </summary>
        /// <remarks>
        /// Get a list of all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of ApiResponse (StockProfilesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<StockProfilesResponse>> CallListAsyncWithHttpInfo (string apiKey, int? page, int? pageSize);
        /// <summary>
        /// Officers
        /// </summary>
        /// <remarks>
        /// Get the officers of the company.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of OfficersResponse</returns>
        System.Threading.Tasks.Task<OfficersResponse> OfficersAsync (string apiKey, string fullTicker);

        /// <summary>
        /// Officers
        /// </summary>
        /// <remarks>
        /// Get the officers of the company.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of ApiResponse (OfficersResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OfficersResponse>> OfficersAsyncWithHttpInfo (string apiKey, string fullTicker);
        /// <summary>
        /// Profile
        /// </summary>
        /// <remarks>
        /// Returns the profile of a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of StockProfileResponse</returns>
        System.Threading.Tasks.Task<StockProfileResponse> ProfileAsync (string apiKey, string fullTicker);

        /// <summary>
        /// Profile
        /// </summary>
        /// <remarks>
        /// Returns the profile of a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of ApiResponse (StockProfileResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<StockProfileResponse>> ProfileAsyncWithHttpInfo (string apiKey, string fullTicker);
        /// <summary>
        /// Screener
        /// </summary>
        /// <remarks>
        /// Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of StockProfilesResponse</returns>
        System.Threading.Tasks.Task<StockProfilesResponse> ScreenerAsync (ScreenerRequest body, string apiKey, int? page, int? pageSize);

        /// <summary>
        /// Screener
        /// </summary>
        /// <remarks>
        /// Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of ApiResponse (StockProfilesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<StockProfilesResponse>> ScreenerAsyncWithHttpInfo (ScreenerRequest body, string apiKey, int? page, int? pageSize);
        /// <summary>
        /// Search
        /// </summary>
        /// <remarks>
        /// Search among all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of StockProfilesResponse</returns>
        System.Threading.Tasks.Task<StockProfilesResponse> SearchAsync (string apiKey, string text, int? page, int? pageSize);

        /// <summary>
        /// Search
        /// </summary>
        /// <remarks>
        /// Search among all the available stocks.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of ApiResponse (StockProfilesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<StockProfilesResponse>> SearchAsyncWithHttpInfo (string apiKey, string text, int? page, int? pageSize);
        /// <summary>
        /// Splits
        /// </summary>
        /// <remarks>
        /// Get all the splits for a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>Task of SplitsResponse</returns>
        System.Threading.Tasks.Task<SplitsResponse> SplitsAsync (string apiKey, string fullTicker, int? page, int? pageSize);

        /// <summary>
        /// Splits
        /// </summary>
        /// <remarks>
        /// Get all the splits for a given stock.
        /// </remarks>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>Task of ApiResponse (SplitsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SplitsResponse>> SplitsAsyncWithHttpInfo (string apiKey, string fullTicker, int? page, int? pageSize);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class StocksApi : IStocksApi
    {
        private Equibles.Stocks.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StocksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StocksApi(String basePath)
        {
            this.Configuration = new Equibles.Stocks.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Equibles.Stocks.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StocksApi"/> class
        /// </summary>
        /// <returns></returns>
        public StocksApi()
        {
            this.Configuration = Equibles.Stocks.Client.Configuration.Default;

            ExceptionFactory = Equibles.Stocks.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StocksApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StocksApi(Equibles.Stocks.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Equibles.Stocks.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Equibles.Stocks.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Equibles.Stocks.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Equibles.Stocks.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// List Stocks Get a list of all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>StockProfilesResponse</returns>
        public StockProfilesResponse CallList (string apiKey, int? page, int? pageSize)
        {
             ApiResponse<StockProfilesResponse> localVarResponse = CallListWithHttpInfo(apiKey, page, pageSize);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Stocks Get a list of all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>ApiResponse of StockProfilesResponse</returns>
        public ApiResponse< StockProfilesResponse > CallListWithHttpInfo (string apiKey, int? page, int? pageSize)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->CallList");

            var localVarPath = "./stocks/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CallList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfilesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfilesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfilesResponse)));
        }

        /// <summary>
        /// List Stocks Get a list of all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of StockProfilesResponse</returns>
        public async System.Threading.Tasks.Task<StockProfilesResponse> CallListAsync (string apiKey, int? page, int? pageSize)
        {
             ApiResponse<StockProfilesResponse> localVarResponse = await CallListAsyncWithHttpInfo(apiKey, page, pageSize);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Stocks Get a list of all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of ApiResponse (StockProfilesResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StockProfilesResponse>> CallListAsyncWithHttpInfo (string apiKey, int? page, int? pageSize)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->CallList");

            var localVarPath = "./stocks/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CallList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfilesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfilesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfilesResponse)));
        }

        /// <summary>
        /// Officers Get the officers of the company.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>OfficersResponse</returns>
        public OfficersResponse Officers (string apiKey, string fullTicker)
        {
             ApiResponse<OfficersResponse> localVarResponse = OfficersWithHttpInfo(apiKey, fullTicker);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Officers Get the officers of the company.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>ApiResponse of OfficersResponse</returns>
        public ApiResponse< OfficersResponse > OfficersWithHttpInfo (string apiKey, string fullTicker)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Officers");
            // verify the required parameter 'fullTicker' is set
            if (fullTicker == null)
                throw new ApiException(400, "Missing required parameter 'fullTicker' when calling StocksApi->Officers");

            var localVarPath = "./stocks/officers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (fullTicker != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fullTicker", fullTicker)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Officers", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OfficersResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (OfficersResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OfficersResponse)));
        }

        /// <summary>
        /// Officers Get the officers of the company.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of OfficersResponse</returns>
        public async System.Threading.Tasks.Task<OfficersResponse> OfficersAsync (string apiKey, string fullTicker)
        {
             ApiResponse<OfficersResponse> localVarResponse = await OfficersAsyncWithHttpInfo(apiKey, fullTicker);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Officers Get the officers of the company.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of ApiResponse (OfficersResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OfficersResponse>> OfficersAsyncWithHttpInfo (string apiKey, string fullTicker)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Officers");
            // verify the required parameter 'fullTicker' is set
            if (fullTicker == null)
                throw new ApiException(400, "Missing required parameter 'fullTicker' when calling StocksApi->Officers");

            var localVarPath = "./stocks/officers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (fullTicker != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fullTicker", fullTicker)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Officers", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OfficersResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (OfficersResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OfficersResponse)));
        }

        /// <summary>
        /// Profile Returns the profile of a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>StockProfileResponse</returns>
        public StockProfileResponse Profile (string apiKey, string fullTicker)
        {
             ApiResponse<StockProfileResponse> localVarResponse = ProfileWithHttpInfo(apiKey, fullTicker);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Profile Returns the profile of a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>ApiResponse of StockProfileResponse</returns>
        public ApiResponse< StockProfileResponse > ProfileWithHttpInfo (string apiKey, string fullTicker)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Profile");
            // verify the required parameter 'fullTicker' is set
            if (fullTicker == null)
                throw new ApiException(400, "Missing required parameter 'fullTicker' when calling StocksApi->Profile");

            var localVarPath = "./stocks/profile";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (fullTicker != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fullTicker", fullTicker)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Profile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfileResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfileResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfileResponse)));
        }

        /// <summary>
        /// Profile Returns the profile of a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of StockProfileResponse</returns>
        public async System.Threading.Tasks.Task<StockProfileResponse> ProfileAsync (string apiKey, string fullTicker)
        {
             ApiResponse<StockProfileResponse> localVarResponse = await ProfileAsyncWithHttpInfo(apiKey, fullTicker);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Profile Returns the profile of a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <returns>Task of ApiResponse (StockProfileResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StockProfileResponse>> ProfileAsyncWithHttpInfo (string apiKey, string fullTicker)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Profile");
            // verify the required parameter 'fullTicker' is set
            if (fullTicker == null)
                throw new ApiException(400, "Missing required parameter 'fullTicker' when calling StocksApi->Profile");

            var localVarPath = "./stocks/profile";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (fullTicker != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fullTicker", fullTicker)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Profile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfileResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfileResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfileResponse)));
        }

        /// <summary>
        /// Screener Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>StockProfilesResponse</returns>
        public StockProfilesResponse Screener (ScreenerRequest body, string apiKey, int? page, int? pageSize)
        {
             ApiResponse<StockProfilesResponse> localVarResponse = ScreenerWithHttpInfo(body, apiKey, page, pageSize);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Screener Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>ApiResponse of StockProfilesResponse</returns>
        public ApiResponse< StockProfilesResponse > ScreenerWithHttpInfo (ScreenerRequest body, string apiKey, int? page, int? pageSize)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling StocksApi->Screener");
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Screener");

            var localVarPath = "./stocks/screener";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Screener", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfilesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfilesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfilesResponse)));
        }

        /// <summary>
        /// Screener Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of StockProfilesResponse</returns>
        public async System.Threading.Tasks.Task<StockProfilesResponse> ScreenerAsync (ScreenerRequest body, string apiKey, int? page, int? pageSize)
        {
             ApiResponse<StockProfilesResponse> localVarResponse = await ScreenerAsyncWithHttpInfo(body, apiKey, page, pageSize);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Screener Get a list of the stocks constraint to several criteria. You only need to fill the fields that you want to use as filters.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The criteria used to filter the search results. You only need to fill the fields that you want to use on the search.</param>
        /// <param name="apiKey"></param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of ApiResponse (StockProfilesResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StockProfilesResponse>> ScreenerAsyncWithHttpInfo (ScreenerRequest body, string apiKey, int? page, int? pageSize)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling StocksApi->Screener");
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Screener");

            var localVarPath = "./stocks/screener";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Screener", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfilesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfilesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfilesResponse)));
        }

        /// <summary>
        /// Search Search among all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>StockProfilesResponse</returns>
        public StockProfilesResponse Search (string apiKey, string text, int? page, int? pageSize)
        {
             ApiResponse<StockProfilesResponse> localVarResponse = SearchWithHttpInfo(apiKey, text, page, pageSize);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search Search among all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>ApiResponse of StockProfilesResponse</returns>
        public ApiResponse< StockProfilesResponse > SearchWithHttpInfo (string apiKey, string text, int? page, int? pageSize)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Search");
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling StocksApi->Search");

            var localVarPath = "./stocks/search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (text != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "text", text)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Search", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfilesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfilesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfilesResponse)));
        }

        /// <summary>
        /// Search Search among all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of StockProfilesResponse</returns>
        public async System.Threading.Tasks.Task<StockProfilesResponse> SearchAsync (string apiKey, string text, int? page, int? pageSize)
        {
             ApiResponse<StockProfilesResponse> localVarResponse = await SearchAsyncWithHttpInfo(apiKey, text, page, pageSize);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search Search among all the available stocks.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="text">The text to search for.</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 100. (optional, default to 100)</param>
        /// <returns>Task of ApiResponse (StockProfilesResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StockProfilesResponse>> SearchAsyncWithHttpInfo (string apiKey, string text, int? page, int? pageSize)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Search");
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling StocksApi->Search");

            var localVarPath = "./stocks/search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (text != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "text", text)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Search", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StockProfilesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StockProfilesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StockProfilesResponse)));
        }

        /// <summary>
        /// Splits Get all the splits for a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>SplitsResponse</returns>
        public SplitsResponse Splits (string apiKey, string fullTicker, int? page, int? pageSize)
        {
             ApiResponse<SplitsResponse> localVarResponse = SplitsWithHttpInfo(apiKey, fullTicker, page, pageSize);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Splits Get all the splits for a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>ApiResponse of SplitsResponse</returns>
        public ApiResponse< SplitsResponse > SplitsWithHttpInfo (string apiKey, string fullTicker, int? page, int? pageSize)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Splits");
            // verify the required parameter 'fullTicker' is set
            if (fullTicker == null)
                throw new ApiException(400, "Missing required parameter 'fullTicker' when calling StocksApi->Splits");

            var localVarPath = "./stocks/splits";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (fullTicker != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fullTicker", fullTicker)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Splits", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SplitsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SplitsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SplitsResponse)));
        }

        /// <summary>
        /// Splits Get all the splits for a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>Task of SplitsResponse</returns>
        public async System.Threading.Tasks.Task<SplitsResponse> SplitsAsync (string apiKey, string fullTicker, int? page, int? pageSize)
        {
             ApiResponse<SplitsResponse> localVarResponse = await SplitsAsyncWithHttpInfo(apiKey, fullTicker, page, pageSize);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Splits Get all the splits for a given stock.
        /// </summary>
        /// <exception cref="Equibles.Stocks.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey"></param>
        /// <param name="fullTicker">The fully qualified ticker of the stock. Example: AAPL.XNAS</param>
        /// <param name="page">The number of the page to request. (optional, default to 1)</param>
        /// <param name="pageSize">The number of elements in each page. Max value: 1000. (optional, default to 1000)</param>
        /// <returns>Task of ApiResponse (SplitsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SplitsResponse>> SplitsAsyncWithHttpInfo (string apiKey, string fullTicker, int? page, int? pageSize)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling StocksApi->Splits");
            // verify the required parameter 'fullTicker' is set
            if (fullTicker == null)
                throw new ApiException(400, "Missing required parameter 'fullTicker' when calling StocksApi->Splits");

            var localVarPath = "./stocks/splits";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", apiKey)); // query parameter
            if (fullTicker != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fullTicker", fullTicker)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (pageSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "pageSize", pageSize)); // query parameter
            // authentication (Query String) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Splits", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SplitsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SplitsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SplitsResponse)));
        }

    }
}
